/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procorr;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class FrmLogin extends javax.swing.JFrame {

    public FrmLogin() {
        initComponents();
        
        lablogginn.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseReleased(MouseEvent e) {
                logginn();
            }
            @Override
            public void mouseEntered(MouseEvent e) { 
                lablogginn.setBackground(new Color(0,80,113));
                lablogginn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            }
            @Override
            public void mouseExited(MouseEvent e) {
                lablogginn.setBackground(new Color(0,166,235));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        pnlInput = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        lblSignin = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        pwdPass = new javax.swing.JPasswordField();
        lablogginn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProCorr AS - Logg inn");
        setBackground(new java.awt.Color(0, 102, 204));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setName("frmLogin"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        pnlLogin.setMaximumSize(new java.awt.Dimension(1000, 600));
        pnlLogin.setMinimumSize(new java.awt.Dimension(1000, 600));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loginleft.png"))); // NOI18N
        lblImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblImage.setAlignmentY(0.0F);
        lblImage.setFocusable(false);
        lblImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImage.setIconTextGap(0);
        lblImage.setRequestFocusEnabled(false);
        lblImage.setVerifyInputWhenFocusTarget(false);
        pnlLogin.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlInput.setBackground(new java.awt.Color(0, 106, 150));
        pnlInput.setMaximumSize(new java.awt.Dimension(500, 600));
        pnlInput.setMinimumSize(new java.awt.Dimension(500, 600));
        pnlInput.setPreferredSize(new java.awt.Dimension(500, 600));
        pnlInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setBackground(new java.awt.Color(0, 106, 150));
        txtName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtName.setMaximumSize(new java.awt.Dimension(300, 50));
        txtName.setMinimumSize(new java.awt.Dimension(300, 50));
        txtName.setNextFocusableComponent(lblPass);
        txtName.setPreferredSize(new java.awt.Dimension(300, 50));
        txtName.setSelectedTextColor(new java.awt.Color(51, 102, 255));
        txtName.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        pnlInput.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 300, 50));

        lblError.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 102, 102));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setFocusable(false);
        lblError.setMaximumSize(new java.awt.Dimension(300, 50));
        lblError.setMinimumSize(new java.awt.Dimension(300, 50));
        lblError.setPreferredSize(new java.awt.Dimension(300, 50));
        pnlInput.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, 20));

        lblSignin.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblSignin.setForeground(new java.awt.Color(255, 255, 255));
        lblSignin.setText("Logg inn");
        lblSignin.setFocusable(false);
        pnlInput.add(lblSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 110, 156, 57));

        lblPass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Passord:");
        lblPass.setFocusable(false);
        pnlInput.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 305, -1, -1));

        lblUsername.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Brukernavn:");
        lblUsername.setFocusable(false);
        pnlInput.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 205, -1, -1));

        pwdPass.setBackground(new java.awt.Color(0, 106, 150));
        pwdPass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pwdPass.setForeground(new java.awt.Color(255, 255, 255));
        pwdPass.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pwdPass.setCaretColor(new java.awt.Color(255, 255, 255));
        pwdPass.setMaximumSize(new java.awt.Dimension(300, 50));
        pwdPass.setMinimumSize(new java.awt.Dimension(300, 50));
        pwdPass.setPreferredSize(new java.awt.Dimension(300, 50));
        pwdPass.setSelectedTextColor(new java.awt.Color(51, 102, 153));
        pwdPass.setSelectionColor(new java.awt.Color(255, 255, 255));
        pwdPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdPassFocusGained(evt);
            }
        });
        pwdPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        pnlInput.add(pwdPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 300, 50));

        lablogginn.setBackground(new java.awt.Color(0, 166, 235));
        lablogginn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lablogginn.setForeground(new java.awt.Color(255, 255, 255));
        lablogginn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lablogginn.setText("Logg inn");
        lablogginn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lablogginn.setMaximumSize(new java.awt.Dimension(190, 40));
        lablogginn.setMinimumSize(new java.awt.Dimension(190, 40));
        lablogginn.setOpaque(true);
        lablogginn.setPreferredSize(new java.awt.Dimension(190, 40));
        pnlInput.add(lablogginn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        pnlLogin.add(pnlInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        txtName.selectAll();
    }//GEN-LAST:event_txtNameFocusGained

    private void pwdPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPassFocusGained
        // TODO add your handling code here:
        pwdPass.selectAll();
    }//GEN-LAST:event_pwdPassFocusGained

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            logginn();
        }
    }//GEN-LAST:event_loginKeyPressed

    public void logginn(){
        try {
            Kontroll.kontroll.startConnection();
            Kontroll.kontroll.loginCorrect(txtName.getText(), pwdPass.getPassword());
            MainFrame tasks = new MainFrame();  
            lblError.setText("Laster");
            tasks.setVisible(true);
            FrmLogin.this.dispose();
        } catch (Exception e){
            lblError.setText(e.getMessage());
            System.out.println(e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new FrmLogin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lablogginn;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblSignin;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}